export default {
    products: [
    {
        _id: '1',
        name: 'Fitted Mask',
        category: 'Masks',
        image: '/images/d1.jpg',
        price: 12.99,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Set of 5 Mask',
        category: 'Masks',
        image: '/images/d2.jpg',
        price: 9.99,
        brand: 'Nike',
        rating: 4.2,
        numReviews: 8,
        countInStock: 5,
    },
    {
        _id: '3',
        name: 'Nike Mask',
        category: 'Masks',
        image: '/images/d3.jpg',
        price: 15.99,
        brand: 'Nike',
        rating: 4.1,
        numReviews: 6,
        countInStock: 8,
    },
    {
        _id: '4',
        name: 'Fitted Mask',
        category: 'Masks',
        image: '/images/d4.jpg',
        price: 17.99,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 7,
        countInStock: 6,
    },
    {
        _id: '5',
        name: 'Set of Gloves',
        category: 'Gloves',
        image: '/images/d9.jpg',
        price: 12.99,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 4,
    },
]
}